### ISSUE TITLE
Redirect sites are not supported

### ISSUE THREAD

**Issue by jenda77** [codefog/contao-cookiebar#14]
I have created a redirect site and choose it per your button. But this site type does not work and no link will be created. Could you add the support for any site typ, please, or tell me how I can fix it by my own? Thank you.

**Comment by qzminski** [comment]
The "read more" link works with every page type so with internal redirect as well.

**Comment by jenda77** [comment]
Unfortunately, my link does not work.

**Comment by qzminski** [comment]
I cannot reproduce the issue locally so you will have to debug it on your own.
