### ISSUE TITLE
Path with folder URLs activated

### ISSUE THREAD

**Issue by de-es** [codefog/contao-cookiebar#15]
When folder URLs are enabled in the front end configuration and I accept the cookie on a subpage like

`http://mydomain.com/products/myproduct.html`

the cookie bar will return on other pages outside this folder. This is because the cookie path is set to `/products/`.

Shouldn't the root path be set in the setCookieBar function?

**Comment by qzminski** [comment]
Can you check if 1.1.1 fixes that issue?

https://github.com/codefog/contao-cookiebar/archive/hotfix/1.1.1.zip

**Comment by de-es** [comment]
Works like a charm. Thanks for your quick response.

**Comment by qzminski** [comment]
I am releasing a new version then.
