### ISSUE TITLE
Feature Request: Repleace TinyMCE with an input field

### ISSUE THREAD

**Issue by k-webdesign** [codefog/contao-cookiebar#16]
Hi Kamil,

would it be possible to replace the "Cookies Information" input with the TinyMCE text editor? This makes me create neatly arranged texts (paragraphs, bold words, etc.).

I'd be very happy to have this feature - also paid, if needed. 

Bye,
Kim

**Comment by niebuhrhood** [comment]
Hi Kim, 

with all due respect: try to edit the cookiebar_default.html5 template.
In real life you won't change it that often... ;-)

**Comment by qzminski** [comment]
The main purpose of this extension is just to notify the visitor about the cookies. More detailed text can be put on an individual page, that's what the details page setting is for. Please also see https://github.com/codefog/contao-cookiebar/issues/9.

If you have a strong need to place HTML in there, I would follow the @niebuhrhood suggestion.
