### ISSUE TITLE
Link to details page, doesn't work across other website roots.

### ISSUE THREAD

**Issue by justinwasilenko** [codefog/contao-cookiebar#17]
First, thanks for the plugin and the work you are putting in.

Second,
I have a few websites with multiple languages. When setting the details page from one language to another in a different root the link won't work to the other website root.
Example:
German Site -> German Details Page
English Site -> English Details Page
Russian Site -> English Details Page ---  This doesn't work. The link in the back end is set correctly. But on the front end the link points to a Russian details page.

Site is running the changelanguage extension and has folders enabled for the url i.e. website.com/de

**Comment by qzminski** [comment]
Do I understand correctly that you want the cookiebar link point to ```http://example.com/en/cookie-policy.html``` when someone enters ```http://example.com/ru/```?

**Comment by justinwasilenko** [comment]
Yep you got it.

**Comment by qzminski** [comment]
Can you try the ```hotfix/1.1.2``` branch?

https://github.com/codefog/contao-cookiebar/tree/hotfix/1.1.2
