### ISSUE TITLE
More accessibility for the cookiebar

### ISSUE THREAD

**Issue by MacKP** [codefog/contao-cookiebar#19]
Hi and thx for this handy module!
I use this for more and more pages. And I have made some Template changes for accessibility. Would be nice if you could implement them for everyone:

```
<aside id="cookiebar" class="<?php echo $this->position; ?>" role="complementary" aria-describedby="dialog1Desc">
    <span id="dialog1Desc" aria-live="assertive" role="alert">
        <?php echo $this->message; ?>
            <?php if ($this->more): ?>
                <a class="cookiebar-more" href="<?php echo $this->moreHref; ?>" title="Weitere Infromationen zu Cookies finden Sie unter Datenschutz / Impressum">Weitere Infromationen</a>
            <?php endif; ?>
        </span>
    <button onclick="setCookieBar('<?php echo $this->cookie; ?>'); return false;"><?php echo $this->button; ?></button>
</aside>
```

First I use this at the top (so Screenreader get this also at first).
I changed the <div> into an <asid> and then used an role and aria-describedby. The Link for more Information need to be before the button (right Order for Screenreader).
It would be nice if the $this->more would be an extra Text only for the cookiebar (for accessiblility we need an extra Text here.. not only 'more').

regards

**Comment by qzminski** [comment]
Implemented in 8353788b8ad687391603bdf4745645862c18f76a.
