### ISSUE TITLE
Improve responsive design and use on one page website

### ISSUE THREAD

**Issue by birdmedia** [codefog/contao-cookiebar#20]
The cookiebar is set to 100% width while the padding left and right is set in pixels which causes negative effects on responsive websites. The padding should be set in percent as well:

E.g. #cookiebar -> width: 96%, padding: 8px 2% 8px 2%;

The detail page can only be selected from the contao site tree which makes it difficult to link to an anker on the same page without changing the template.

**Comment by qzminski** [comment]
How about having the ```box-sizing: border-box``` instead?

**Comment by birdmedia** [comment]
Should work as well :)

**Comment by djoesch** [comment]
Another point on the CSS. Pleas make a "z-index: 999999;" on class ".cookiebar". Cookiebar is designed to be on the top layer, but many websites use the first layers 0-99 on other DIVs.

**Comment by qzminski** [comment]
@djoesch the z-index will not be changed because that value should be adjusted individually. For example the current z-index value was fine for me for almost all of websites whereas yours would conflict with the lightbox I use (cookiebar should appear below the modal window).

**Comment by qzminski** [comment]
Implemented in 979ab0e0b7a2f34e6688abd533212c93c4f1eff8.
