### ISSUE TITLE
Read more ... -Link wrong language

### ISSUE THREAD

**Issue by Alibi-Contao** [codefog/contao-cookiebar#23]
Hey
I have a german Website. And now the "Read more link is in english and not in german:
"Read more ..." instead of "Weiterlesen ..."
If i copy the file "default.php" from languages>en to the directory languages>de it works correctly.
Should the default.php file be in any language directory?
Or is there another solution?

**Comment by qzminski** [comment]
Fixed in 637c7b83b9404a7d384df1a53be77433c2f5c6c9. Please update your version to 1.3.1.
