### ISSUE TITLE
Compatibility for Contao 4

### ISSUE THREAD

**Issue by bastibuck** [codefog/contao-cookiebar#26]
Hey Kamil,

tested your extension in Contao 4 (Up to date Standard-Edition) - seems to work fine. Could you update your _composer.json_ so we can install from composer instead manually? 

Thanks :-)

**Comment by qzminski** [comment]
Fixed in 2b970ca. Just released version 1.3.2.

**Comment by mpitz** [comment]
In Contao 4.4.6 I can't find the options in the Root-Page-Settings.
