### ISSUE TITLE
Page picker for details page not working in Contao 4.4. LTS

### ISSUE THREAD

**Issue by bezin** [codefog/contao-cookiebar#30]
Hello there,

I just installed this extension in a Contao 4.4 installation. It seems the page picker for the details page is not working. I figure it might be because of the new dca picker?

![image](https://user-images.githubusercontent.com/4400435/27447658-1d598f00-5782-11e7-9cc8-4e84e6944e48.png)

**Comment by qzminski** [comment]
This is a Contao core issue – see https://github.com/contao/core-bundle/issues/883.
