### ISSUE TITLE
Cookiebar is not displayed anymore

### ISSUE THREAD

**Issue by kristinamuc** [codefog/contao-cookiebar#40]
Cookibar 1.4.0 with Contao 3.5.34 is just not working anymore.
Thanks for help.

**Comment by kristinamuc** [comment]
![image5](https://user-images.githubusercontent.com/37865602/38026615-0fbbde66-328d-11e8-8cd8-2a725c789bbc.png)

Backend is everything okay. But there is nothing displayed in frontend.

**Comment by qzminski** [comment]
1. Can you check if the page source contains any cookiebar markup? Just search for the `cookiebar` term.
2. Do you get any JS errors in console?
3. Do you perhaps have this website online and can provide the URL for frontend? No backend access is needed.

**Comment by kristinamuc** [comment]
You can check it here:
https://www.persy.de/home/

Please only try home. On the other pages I use a HTML Cookie in the page Templates and therefore a Cookie Banner will appear. 
I can leave it this way until tomorrow afternoon. But then I need to add the HTML Cookie again to avoid problems.

**Comment by qzminski** [comment]
Please add the HTML cookie again then. I will keep you updated about the progress on solving this issue here.

**Comment by qzminski** [comment]
See #41.
