### ISSUE TITLE
Cookiebar frontend-problem 

### ISSUE THREAD

**Issue by farbschmelz** [codefog/contao-cookiebar#41]
Dzien Dobry ;)

we do have a problem with Cookiebar on one website. Backend wise everything seems to be okay but the banner doesn´t show up.

**Status**
· Contao 3.3.5 (will be updated soon^^), cookiebar 1.4.0
· extension is active and filled with information in the website root
· no cookie is set, cache is empty
· js and css are present in the dom but the cookiebar-div wont show up
· no js-errors within browser, no php-errors (contao-log)

**Solution steps**
· tried to add a "new" fe_page without customizations > no success
· added the shortcode to {{cookie_bar|uncached}} to the fe_page > no success
· added the code from cookiebar_default.html5 manually > div is loaded, but empty

Would be really glad if you can give me a hint 👍 

Kind Regards
MS

**Comment by qzminski** [comment]
Thanks for the detailed explanation. I am not able to reproduce the issue locally but you're not the first to report the issue so there must be some error.

Have you got this website online? If so, could you provide me Contao + FTP access to it (via private e-mail) for debugging purposes?

**Comment by farbschmelz** [comment]
I´ll send you the logins (but have to get a restricted ftp-access first). Thank you!

**Comment by qzminski** [comment]
@farbschmelz any news on this?

**Comment by Metis77** [comment]
>  div is loaded, but empty
Same issue on Contao 4.4 if Contao Cache is enabled.

**Comment by qzminski** [comment]
I have just released 2.0.0 which should solve the cache problems once and for all. The new version no longer depends on the server cookie check but is JS only in that matter.

Here is a checklist for the update 1.4 –> 2.0:

1. Update the database (or Contao 4 will throw an error in frontend)
2. Review the cookie bar settings
3. Review your styles or custom template as they have been changed significantly in the new version

**Comment by kristinamuc** [comment]
unfortunately it does not work here: persy.de
although it is to see in Source Code of the website, the cookie banner does not appar.
![cookibar](https://user-images.githubusercontent.com/37865602/38558711-404062de-3cd1-11e8-8eac-6892ebfb1e50.png)

**Comment by kristinamuc** [comment]
Danke für die Info mit dem Javascript. Ich habe die fe_page nicht angefasst, oder muss ich da was ändern? Ich verstehe deine Antwort nicht so ganz. Was soll ich tun?

Ja, die eigene Cookibar Lösung vom Theme ist aber Template-basiert, sobald der User z.B. von einem einspaltigen Layout auf ein zweispaltiges klickt, bekommt er wieder die Cookie-Abfrage. Darum gefällt mir das Plugin auf Seitenstruktur eingebunden besser.
Danke

**Comment by Metis77** [comment]
Did you enable the default CSS in the page settings?
![bildschirmfoto 2018-04-10 um 15 57 08](https://user-images.githubusercontent.com/1408361/38561323-0afde69e-3cd8-11e8-9f45-aa0be1534f2f.png)

@qzminski after a fresh install, "embed default css" should be activated, to present a visible plugin out of the box.

**Comment by kristinamuc** [comment]
great,  thank you. 
With "embed default css" enabled it works. 
Thanks!

**Comment by qzminski** [comment]
It will be default in SQL definition in 2.0.1. This option was enabled by default already when creating a new website root, but since people usually install the extension *after* adding a new root page, this way should be more convenient.

**Comment by kristinamuc** [comment]
While version 2.0.0 worked fine ( after enabling css) version 2.0.1. gives an error when saving it:
![cooki1](https://user-images.githubusercontent.com/37865602/38619654-efd10930-3d9c-11e8-9b5e-04dc05ca534f.png)
![cooki2](https://user-images.githubusercontent.com/37865602/38619668-f97646a8-3d9c-11e8-865d-b2b9313ac96a.png)

**Comment by qzminski** [comment]
You have to update the database.

**Comment by kristinamuc** [comment]
yes, it solved it. 
I thought it was done automatically before during the update ...
My fault, thanks for you help.
