### ISSUE TITLE
cookiebar isn´t visible if server cache is enabled

### ISSUE THREAD

**Issue by simon-1977** [codefog/contao-cookiebar#43]
The cookiebar isn´t visible in the frontend if server cache (site structure) ist enabled.
Contao 4.4.17

**Comment by qzminski** [comment]
What version of cookiebar have you got installed?

**Comment by simon-1977** [comment]
Since yesterday 1.4.1

**Comment by qzminski** [comment]
Please use version 2.0 which does not rely on the server cache.
