### ISSUE TITLE
Unknown insert tag flag "uncached" in {{cookie_bar|uncached}}

### ISSUE THREAD

**Issue by operatorone** [codefog/contao-cookiebar#44]
Hi there,

I have a lot of entries in my system log which say 

`Unknown insert tag flag "uncached" in {{cookie_bar|uncached}}`

I use Contao 4.4.18. Any ideas why they appear?

Cheers, operatorone

**Comment by qzminski** [comment]
Please use version 2.x of the extension, as 1.x is no longer supported.

**Comment by operatorone** [comment]
Thanks for the info 😀
