### ISSUE TITLE
Cookiebar does not appear on screen in Contao 3.5

### ISSUE THREAD

**Issue by Schneetiger** [codefog/contao-cookiebar#46]
I use contao 3.5 and the cookiebar version 2.0.1. I have got the problem that the cookiebar does not appear on screen as it should and did in versions before. I don´t have this phenomena at my own website only but also at my customers websites. Before I wrote these lines I checked out having made something wrong but I can´t find any reason having done this. Thanks for some help.

**Comment by qzminski** [comment]
> I have got the problem that the cookiebar does not appear on screen as it should and did in versions before.

In version 2.0 the markup has changed so maybe your custom styling does no longer applies?

Or maybe you haven't checked the option to include default CSS files in the settings?

**Comment by f7o** [comment]
Seems like no css nor any additional JS is loaded after enabling the cookiebar. Using 3.5 as well.

**Comment by qzminski** [comment]
@f7o are you on version 2.0.1? Contao 3.5.4 is a pretty outdated version but it still should work there I think. Can you check if the cookiebar markup is in the page source?

**Comment by f7o** [comment]
Yes i am using the newest cookiebar version. I don't mind that it's a old version of contao cause this website will be closed soon anyway.

The newest version is support using your cookie bar?

**Comment by Schneetiger** [comment]
I use the actual cookiebar version 2.0.1 and Contao 3.5.35. I still have to check how I use the css-code and will BE Back at the weekend.

**Comment by qzminski** [comment]
@f7o yes the newest versions of Contao 3 and 4 are supported. But if something is not working there then it must be a bug.

@Schneetiger okay I am looking forward for your feedback then.

**Comment by Schneetiger** [comment]
@f7o 

⁣Freundliche Grüße
Detlef Rimböck

Gesendet mit BlueMail ​Am 18. Mai 2018, um 08:42, Kamil Kuzminski <notifications@github.com> schrieb:

@f7o yes the newest versions of Contao 3 and 4 are supported. But if something is not working there then it must be a bug.

@Schneetiger okay I am looking forward for your feedback then.

Well, maybe I was wrong. Unfortunatelly I am not at home and have no access to my webhosting. As far as I can see there must be a problem with "http://" and "https://". I can reach my website with both protocols. That ist my fault. So I found out that the cookiebar works fine with "http://"-acces to my website but not with "https://". I wanted to cancel the "http://"-access but something went wrong. There should be no "http://"-acces at all.
I will look at the weekend and then tell the result. Thanks for your pacience so far.
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by f7o** [comment]
I am using `https` only!
For me its not urgent, i will use an alternative. Was just an idea to have it included into contao.

**Comment by qzminski** [comment]
Whether it's `https` or not it should not really matter.  Can you perhaps check if there are any JS errors in the browser console log in the frontend?

**Comment by f7o** [comment]
No JS Errors, no actual JS import for coobiebar, no CSS file importet for cookiebar.

**Comment by qzminski** [comment]
Are you by chance using a custom `fe_` template that does not allow to include the stuff via "regular" Contao way, that is using `$GLOBALS`?

**Comment by ways2web** [comment]
same issue ob my site.

**Comment by qzminski** [comment]
I have just installed the cookiebar from ER2 on a raw Contao 3.5 + Music Academy setup and it works just fine. Do you have any other extensions installed or use a custom `fe_` template?

**Comment by f7o** [comment]
* yes i use a custom `fe_` template
* yes i am using xhtml templates

Would be nice to get any info about what are the requirements to use this extension.

**Comment by qzminski** [comment]
I have updated the docs in d5716a6.

**Comment by Schneetiger** [comment]
Sorry for answering so late. At present I´m very busy in my main job. I´ll check it out and will give you an answer soon. Thanks a lot for your patience.
 

Gesendet: Samstag, 19. Mai 2018 um 10:13 Uhr
Von: "Kamil Kuzminski" <notifications@github.com>
An: codefog/contao-cookiebar <contao-cookiebar@noreply.github.com>
Cc: Schneetiger <dmr01@gmx.de>, Mention <mention@noreply.github.com>
Betreff: Re: [codefog/contao-cookiebar] Cookiebar does not appear on screen in Contao 3.5 (#46)


Whether it's https or not it should not really matter. Can you perhaps check if there are any JS errors in the browser console log in the frontend?

**Comment by Schneetiger** [comment]
I have some other extentions installed, for example some by rocksolid. No, I don´t use a custom fe_template but I found cookiebar_templates an da stupid question: Have I to use one of them in any manual way? In your describtion is nothing mentioned an di don´t think so.

What about deinstalling it first and reinstalling then?

 

Gesendet: Donnerstag, 24. Mai 2018 um 08:30 Uhr
Von: "Kamil Kuzminski" <notifications@github.com>
An: codefog/contao-cookiebar <contao-cookiebar@noreply.github.com>
Cc: Schneetiger <dmr01@gmx.de>, Mention <mention@noreply.github.com>
Betreff: Re: [codefog/contao-cookiebar] Cookiebar does not appear on screen in Contao 3.5 (#46)


I have just installed the cookiebar from ER2 on a raw Contao 3.5 + Music Academy setup and it works just fine. Do you have any other extensions installed or use a custom fe_ template?

**Comment by Schneetiger** [comment]
I use html5 only!
 

Gesendet: Donnerstag, 24. Mai 2018 um 17:16 Uhr
Von: "Kamil Kuzminski" <notifications@github.com>
An: codefog/contao-cookiebar <contao-cookiebar@noreply.github.com>
Cc: Schneetiger <dmr01@gmx.de>, Mention <mention@noreply.github.com>
Betreff: Re: [codefog/contao-cookiebar] Cookiebar does not appear on screen in Contao 3.5 (#46)


I have updated the docs in d5716a6.

**Comment by Schneetiger** [comment]
I use these extensions (look at the escreenshot).
 

Gesendet: Donnerstag, 24. Mai 2018 um 17:16 Uhr
Von: "Kamil Kuzminski" <notifications@github.com>
An: codefog/contao-cookiebar <contao-cookiebar@noreply.github.com>
Cc: Schneetiger <dmr01@gmx.de>, Mention <mention@noreply.github.com>
Betreff: Re: [codefog/contao-cookiebar] Cookiebar does not appear on screen in Contao 3.5 (#46)


I have updated the docs in d5716a6.

**Comment by Schneetiger** [comment]
Hi Kamil,

 

after having updated your cookiebar, everything seems to work fine so far. I use the theme 80/20 by rocksolid and it seems that cookiebar uses their main.css as base for its style. Therefore I send you some screenshots and an extract from the main.css to enable you to answer my following question.


	Does the cookiebar use this main.css for getting styled? I think, yes.
	This seems to be done by activating both checkboxes at the end of the cookiebar area (look at the screenshot, please).
	Therefore I do not need to activate the cookiebar with an own style, right? I disabled it in my custom.css meanwhile because the activation caused no change in the look.
	On the other hand, if I use no themes (for my customers for example) I have to activate the cookiebar there with an own style to make it visible and adjustable?
	Last question: If I want to display the cookiebar constantly, what input do I have to do in the textbox "cookiebar display interval"? Nothing, 0 or 1?


Thanks a lot for your help and patience. I am looking forward to hearing from you soon for a better understanding how the cookiebar work at present.

 

Greetings

 

Detlef Rimböck

 

Gesendet: Donnerstag, 24. Mai 2018 um 17:16 Uhr
Von: "Kamil Kuzminski" <notifications@github.com>
An: codefog/contao-cookiebar <contao-cookiebar@noreply.github.com>
Cc: Schneetiger <dmr01@gmx.de>, Mention <mention@noreply.github.com>
Betreff: Re: [codefog/contao-cookiebar] Cookiebar does not appear on screen in Contao 3.5 (#46)


I have updated the docs in d5716a6.

**Comment by ways2web** [comment]
I just can't find the problem. I use a custom template.
I see, the display:none does not change and therefore the cookiebar is not shown. :(


z-index is a little bit too low, but this not the problem

**Comment by qzminski** [comment]
@ways2web are you sure you do not have a cookie set already? Do you get any JS errors? Can you ensure that cookiebar.min.js and cookiebar.min.css are included?

Also, if you use a custom template make sure it's compatible with the current 2.1 version you have installed.

**Comment by ways2web** [comment]
i cant find any information about "what is necessary for it" in a custom template.
