### ISSUE TITLE
No "Cookie information" in the root page settings

### ISSUE THREAD

**Issue by extractjan** [codefog/contao-cookiebar#49]
hi,

I just installed cookiebar 2.0.1 (contao 3.5.16) ... and there is no "Cookie information" in the root page settings. Any idea what could be wrong ? 

(can't give access to the backend yet, sorry)

Thanks

**Comment by qzminski** [comment]
Are you sure nothing is there? It should be located at the end of the root page edit form.

Did you install it via Extension Repository or some other way? Have you been prompted to update the database?

**Comment by extractjan** [comment]
oops.. somethin went totally wrong with the installation, it was not complete. now it works.  
thanks
