### ISSUE TITLE
No Cookiebar visible on the frontend.

### ISSUE THREAD

**Issue by kossi26** [codefog/contao-cookiebar#50]
I installed the cookiebar version 2.0.1 on Contao CMS 3.5.31 and it's not  displayed.
I followed the documentation https://github.com/codefog/contao-cookiebar/blob/master/docs/README.md.

**Comment by qzminski** [comment]
Maybe you are using the XHTML page layout which is not supported by `cookiebar`? In order to fix that either create a `cookiebar.xhtml` template based on `cookiebar.html5`, or simply adjust page layout settings accordingly.

**Comment by qzminski** [comment]
Duplicate of #46.
