### ISSUE TITLE
Transform Google Analytics to Opt-In (or offer the opportunity)

### ISSUE THREAD

**Issue by Defcon0** [codefog/contao-cookiebar#53]
Hello,

I saw that in the current release we have an opt-**out** solution. Unfortunately the first companies now here in Germany are sued for not having an opt-**IN** for Google Analytics.

Would it be possible to transform the solution to an opt-in?

Thanks in advance.

Bye

**Comment by qzminski** [comment]
Actually the implementation depends only on you, as the only thing that cookiebar provides by default for opt-in is the default label. That however can be adjusted in the field that appears when you check the checkbox.

To go with opt-in, just follow the documentation: https://github.com/codefog/contao-cookiebar/blob/master/docs/README.md#alternate-method--opt-in
