### ISSUE TITLE
Adblocker remove the cookie bar content

### ISSUE THREAD

**Issue by baumannsven** [codefog/contao-cookiebar#58]
The adguard adblocker removed the content of the cookie bar, if is installed.

Search rule for remove:
- span[class*="cookie"]
- :not(input)[id*="cookie"]

Link to the browser extension:
https://chrome.google.com/webstore/detail/adguard-adblocker/bgnkhhnnamicmpeenaelnjfhikgbkllg

**Comment by qzminski** [comment]
Thanks, but I don't think this is a problem of my extension. It's rather the adblocker wrong configuration.

**Comment by baumannsven** [comment]
Then can you tell me how to tell the blockers to accept the cookie bar?
