### ISSUE TITLE
Can't install the extension over Contao-Manager

### ISSUE THREAD

**Issue by chiron501** [codefog/contao-cookiebar#59]
Hello,
i tried to install your extension with the contao-manager (1.0.2) for Contao LTS (4.4.20) and i get this response:
The "http://packagist.org/p/codefog/contao-cookiebar%243f574762a858237032dc77ef6f692654ed537361224f5d20241d3da75453c450.json" file could not be downloaded (HTTP/1.1 404 Not Found)
Can you tell me what went wrong?

**Comment by qzminski** [comment]
To me it looks like the Packagist error. Please try again in later, maybe the cache did not refresh or something.
