### ISSUE TITLE
Template cookiebar - W3 Validator Combination <span><p id="cookieClose">

### ISSUE THREAD

**Issue by blackbee** [codefog/contao-cookiebar#60]
When checking the website with the W3 Validator it produdes / finds the following error:

![grafik](https://user-images.githubusercontent.com/1532987/43147246-e10523c4-8f62-11e8-8adb-4b4d04648a94.png)

This is the dom rendered code:
 
![grafik](https://user-images.githubusercontent.com/1532987/43147303-037ff42e-8f63-11e8-8128-d402ebbc71ad.png)

**Comment by qzminski** [comment]
The `p#cookieClose` element is not a part of the [official template](https://github.com/codefog/contao-cookiebar/blob/master/templates/cookiebar.html5), so it must be your custom code.
