### ISSUE TITLE
limit cookie lifetime to session

### ISSUE THREAD

**Issue by birdmedia** [codefog/contao-cookiebar#61]
Is it possible to limit the lifetime of the cookie "COOKIEBAR_" to the session? Right now the cookie expires after 20h by default, what makes it a persistent cookie.

**Comment by qzminski** [comment]
Not out of the box but you can use your own JS based on what can be found here: https://github.com/codefog/contao-cookiebar/blob/master/assets/src/cookiebar.js

Then simply adjust the template to include your scripts and that should do it: https://github.com/codefog/contao-cookiebar/blob/master/templates/cookiebar.html5

**Comment by birdmedia** [comment]
Works fine, thank you! Maybe it could be a feature to skip the "expires" parameter in order to create a session cookie?

**Comment by qzminski** [comment]
If there are more votes for this feature then I will definitely consider adding it 😉
