### ISSUE TITLE
Überlappung von Custom Element Leaflet Maps

### ISSUE THREAD

**Issue by Nightwing0815** [codefog/contao-cookiebar#65]
Hallo, 
das Cookiebanner wird durch das CE Leaflet Maps überdeckt, siehe hier: [https://bauwagen-badurach.de/lageplan/](https://bauwagen-badurach.de/lageplan/)

ToM

**Comment by qzminski** [comment]
Sorry, I don't speak German. Can you describe the problem in English?

**Comment by Nightwing0815** [comment]
Oh sorry, I forgot to activate the alerts in here, of course i can write in english. Late, but not too late... :-)
Okay, when you have Leaflet maps installed, you're cookiebar is behind, but i fixed it with the following entry in css:
/* Cookiebar */
.cookiebar {
    z-index:500;
}
Leaflet has z-index 400...

Greetings,

ToM

**Comment by qzminski** [comment]
Thanks for the explanation. I don't think the issue can be resolved in the extension itself because layout things such as `z-index` are specific for every site.
