### ISSUE TITLE
cookiebar doesn't show up

### ISSUE THREAD

**Issue by Fanni-Portier** [codefog/contao-cookiebar#68]
I used the cookiebar a lot and never had any problems.

I once saw the cookiebar but I am not able to recreate it - so I am thinking something is wrong.
I tried to delete all cookies and reload - but it doesn't show up - Is it not working this way?

Now I use it with Contao 4.8.8 (my first time with 4 version).
I can see a cookiebar js, css and html in the sourcecode. But the style is always on display:none.
- Contao 4.8.8
- PHP Version 7.3.17

It's a rather small website and I only use these packages:
- mobile-page-layout-bundle 
- contao_dk_mmenu 
- contao-social-tags 
- contao-rocksolid-columns 
- contao-rocksolid-custom-elements 
- contao-aos
- contao-ce-access

It would be great if you can help me :)
Fanni

**Comment by qzminski** [comment]
Since version 2.2.0 cookiebar uses localStorage to store the state. Thus you should clear the value there and bar should be visible again.

**Comment by Fanni-Portier** [comment]
Thank you very much!
