### ISSUE TITLE
Contao Cookiebar cannot be found in the backend

### ISSUE THREAD

**Issue by oezbekh** [codefog/contao-cookiebar#69]
Hi,
I installed the extension on the website but the extension is not to be found in the backend.

How can I configure the Contao cookie bar in the backend?
Contao version 4.4.48
Contao Cookiebar Version 2.2.1

thank you

**Comment by qzminski** [comment]
The extension settings should be visible in the website root settings at the bottom of the form. Can you send me a screenshot they are not visible after the publish settings?

**Comment by oezbekh** [comment]
Thanks for reply.

here Screenshot 

https://ibb.co/ZGcPV0G

**Comment by qzminski** [comment]
Those are the system settings. Cookiebar is enabled in the **site structure** inside the **website root settings**.

**Comment by qzminski** [comment]
The documentation can be found here: https://github.com/codefog/contao-cookiebar/blob/master/docs/README.md

**Comment by oezbekh** [comment]
Can you send me please Screenshot from site structure inside the website root settings.
