### ISSUE TITLE
#cookiebar position not fixed

### ISSUE THREAD

**Issue by florianniebuhr** [codefog/contao-cookiebar#7]
Hi,

your extension works like a charm, I changed the position for the cookiebar right before the wrapper div, because I don´t want to set the position fixed.

Maybe you change position before the #wrapper, to have all position possibilities?
Following:

/classes/Cookiebar.php
line: 67

#wrapper instead body

So you can set #cookiebar position relative.

**Comment by qzminski** [comment]
Implemented in af70753.
