### ISSUE TITLE
Multiple Accept Buttons

### ISSUE THREAD

**Issue by wschwaiger** [codefog/contao-cookiebar#70]
![Bildschirmfoto 2020-05-25 um 18 38 27](https://user-images.githubusercontent.com/458603/82830785-f7fcd580-9eb6-11ea-9ef4-20a8704e7275.png)
I use the cookiebar with multiple accept buttons, 2 in my case. The close click-event only works on the first one of course not the X in the screenshot. Can you provide a solution were all click-events on all buttons with the [data-cookiebar-accept] attribute are recognized? Many thanks

**Comment by qzminski** [comment]
I have just released 2.3.0 :+1:
