### ISSUE TITLE
Cookiebar not shown

### ISSUE THREAD

**Issue by bixicy** [codefog/contao-cookiebar#71]
Hi,

I installed the cookiebar and activatet in site structure, site root. But I cant see when I open the frontend page. Im using the newest version of contao 4.9.3

**Comment by qzminski** [comment]
Please check if the cookiebar markup is present in the page source code (search for `cookiebar`). You may also need to enable default CSS and/or check whether it conflicts with your styles or not.

**Comment by bixicy** [comment]
I found the issue, the cookiebar was behind a picture.

But a another question, only for mobile, can I change the position? I need from the bottom 20px

**Comment by qzminski** [comment]
Just use your custom CSS to do that.
