### ISSUE TITLE
Multilanguage opt-in

### ISSUE THREAD

**Issue by JensenR** [codefog/contao-cookiebar#73]
On one page the cookiebar opt-in (Google Analytics) works fine (eg. language german). But when I switch to the next language (new pagetree) I see in the frontend an already checked opt-in and all google-analytics cookies are set too. Is ist possible to use the cookiebar with opt-in and more than one language?

**Comment by qzminski** [comment]
The cookiebar is strictly assigned to each website root and the language should not matter, so there likely must be something wrong with your custom JS or [opt-in implementation](https://github.com/codefog/contao-cookiebar/blob/master/docs/README.md#alternate-method--opt-in).
