### ISSUE TITLE
php8 ready

### ISSUE THREAD

**Issue by berecont** [codefog/contao-cookiebar#76]
Hello,
do you have a schedule, to prepare the extension ready for php8?
php8.0 or php8.1 or both

**Comment by Kahmoon** [comment]
Actually i ran into the same problem. Cannot update Contao

**Comment by pepesale** [comment]
For me it worked fine. Updated to Contao 4.13.2 with PHP 8.0.

**Comment by qzminski** [comment]
Thanks, I have just released 2.4.0 stable.
