### ISSUE TITLE
autoload.ini missing

### ISSUE THREAD

**Issue by fritzmg** [codefog/contao-cookiebar#78]
The `autoload.ini` was removed in 5238ac9084385085016acf60f9c447148704be72. However, this can cause the extension to be loaded before the `contao/core-bundle` and thus all its `tl_page` fields will be missing.

Since this is still a `contao-module` and not a `contao-bundle` with a Contao Manager Plugin (where you would set the bundle order) you still need the `autoload.ini` in order to define that it should be loaded _after_ the core.

**Comment by qzminski** [comment]
Thanks, fixed in 2.4.1 :+1:
