### ISSUE TITLE
Cookiebar cannot be installed

### ISSUE THREAD

**Issue by GeccoDesign** [codefog/contao-cookiebar#79]
Tried to reinstall cookiebar v2.4.1 after updating to Contao 4.9.29. All the files are downloaded, it shows up in the Contao Manager, no entry in Contao Backend root page and: there are no entries at all in the database... ? Deleted it, new install, same result.

**Comment by qzminski** [comment]
See https://github.com/codefog/contao-cookiebar/issues/80
