### ISSUE TITLE
Not compatible with anyStores

### ISSUE THREAD

**Issue by Tastaturberuf** [codefog/contao-cookiebar#8]
My extension replaces the createSitemap palette token before: https://github.com/Tastaturberuf/anyStores/blob/master/dca/tl_page.php#L16

Your extension can't find the ```createSitemap;``` token, for replacing, because ist now ```createSitemap,```. 

Why you don't put it on the end from the palettes? 

In my reason i must in the sitemap part because its depentent.

**Comment by qzminski** [comment]
Fixed in 9478fdb. You should do that in your extension as well instead of ```str_replace()```.

**Comment by Tastaturberuf** [comment]
Hi @qzminski,

wow that’s fast. You’re right, everybody should do that. I fix it today.
